server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: restaurant-order
  datasource:
    #url: jdbc:h2:mem:digitest
    #username: sa
    #password:
    url: jdbc:mysql://127.0.0.1:3306/javatwenty?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---

spring:
  profiles: dev
  kafka:
    template:
      default-topic: test-topic
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092


